# Форма 101

In [2]:
import pandas as pd

In [5]:
form_101 = pd.read_hdf('/Users/roman142001/Documents/diplom/dataframe/form101.h5',key='101')

Описание всех столбцов данных можно найти в пдф файлах на гитхабе в папке

In [9]:
form_101

,REGN,PLAN,NUM_SC,A_P,VR,VV,VITG,ORA,OVA,OITGA,ORP,OVP,OITGP,IR,IV,IITG,PRIZ
DT,,,,,,,,,,,,,,,,,
2007-01-01,2838,В,91404,2,2204.0,53.0,2257.0,0.0,57.0,57.0,0.0,270.0,270.0,2204.0,266.0,2470.0,1
2007-01-01,435,А,30114,1,0.0,12901.0,12901.0,0.0,29638.0,29638.0,0.0,32319.0,32319.0,0.0,10220.0,10220.0,1
2007-01-01,435,А,30202,1,118193.0,0.0,118193.0,0.0,0.0,0.0,23203.0,0.0,23203.0,94990.0,0.0,94990.0,1
2007-01-01,435,А,30204,1,11333.0,0.0,11333.0,0.0,0.0,0.0,421.0,0.0,421.0,10912.0,0.0,10912.0,1
2007-01-01,435,А,30213,1,272.0,0.0,272.0,61993.0,0.0,61993.0,61253.0,0.0,61253.0,1012.0,0.0,1012.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-01,1343,А,50208,1,5979723.0,0.0,5979723.0,35323.0,0.0,35323.0,57230.0,0.0,57230.0,5957816.0,0.0,5957816.0,1
2021-12-01,1343,А,50207,1,2616695.0,0.0,2616695.0,15286.0,0.0,15286.0,15405.0,0.0,15405.0,2616576.0,0.0,2616576.0,1
2021-12-01,1343,А,50206,1,63922.0,0.0,63922.0,347.0,0.0,347.0,5.0,0.0,5.0,64264.0,0.0,64264.0,1
2021-12-01,1343,А,30243,2,631.0,0.0,631.0,37.0,0.0,37.0,475.0,0.0,475.0,1069.0,0.0,1069.0,1
2021-12-01,2307,А,42502,2,16629000.0,0.0,16629000.0,76832000.0,0.0,76832000.0,76200000.0,0.0,76200000.0,15997000.0,0.0,15997000.0,1